### ISSUE TITLE
Start menu entries missing in windows 10

### ISSUE THREAD

**Issue by icdragn** [randomnoun/ddclient-nsis#3]
The installation went fine on Windows 10, but the convenience shortcuts did not end up in the Start Menu. I can run ddclient from the command line using:

"C:\Program Files (x86)\ddclient\ddclient.exe" -foreground -file "C:\Program Files (x86)\ddclient\ddclient.conf" -cache "C:\Users\username\AppData\Local\ddclient.cache"

I did check that my ip was updated, and it was, so the service works. But the ddclient-related processes are killed when the command window is shutdown.

Perhaps the shortcuts were installed to a location that Windows 10 doesn't use for it's Start Menu; where does the installer place the convenience shortcuts? Alternatively, could you provide the details on the commands used in the shortcuts so that I might create my own?

Thanks,
David

**Comment by knoxg** [comment]
You could try checking to see whether any shortcuts have been created in 
%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ddclient

On my machine there's 6 shortcuts there:

Open ddclient.conf in notepad - C:\WINDOWS\system32\notepad.exe C:\Program Files\ddclient\ddclient.conf
Start ddclient console - "C:\Program Files\ddclient\ddclient.exe" -foreground -file "C:\Program Files\ddclient\ddclient.conf" -cache "C:\Users\knoxg\AppData\Local\ddclient.cache"
Start ddclient service - C:\Windows\System32\net.exe start ddclient
Stop ddclient service - C:\Windows\System32\net.exe stop ddclient
ddclient website - http://www.randomnoun.com/wp/2013/08/19/a-dynamic-dns-client-for-windows/
Uninstall - "C:\Program Files\ddclient\Uninstall.exe"

I still use Classic Shell which picks up that start menu location, but if Windows 10 doesn't do that could try dragging those shortcuts into the Windows 10 start menu ?
