### ISSUE TITLE
Can't run due to missing dependencies?

### ISSUE THREAD

**Issue by JustinBrow** [randomnoun/ddclient-nsis#6]
Attempted to run application but was presented with 2 errors "libcrypto-1_1-x64__.dll is missing" & "libssl-1_1-x64__.dll is missing".  
  
Downloaded pre-compiled OpenSSL 1.1.1k DLLs, specifically the ones compiled by firedaemon (if that matters), found here, [https://wiki.openssl.org/index.php/Binaries](url), and put them in the ddclient folder and renamed them to add 2 underscores before the file extension.  
  
Application now returns error  
`Can't load 'C:\Users\{snip}\AppData\Local\Temp\par-4a757374696e\cache-f6d413a946a68811a62a958c4938e0cf83468dc3\ed365286.xs.dll' fo
r module Net::SSLeay: load_file:The specified module could not be found at <embedded>/DynaLoader.pm line 193.
  at <embedded>/PAR/Heavy.pm line 95.
Compilation failed in require at C:\Users\{snip}\AppData\Local\Temp\par-4a757374696e\cache-f6d413a946a68811a62a958c4938e0cf83468dc
3\inc\lib/IO/Socket/SSL.pm line 19.
BEGIN failed--compilation aborted at C:\Users\{snip}\AppData\Local\Temp\par-4a757374696e\cache-f6d413a946a68811a62a958c4938e0cf834
68dc3\inc\lib/IO/Socket/SSL.pm line 19.
Compilation failed in require at script/ddclient line 34.
BEGIN failed--compilation aborted at script/ddclient line 34.`

**Comment by tm-107** [comment]
Hi,
same problem here ...

ddclient out of the box, nothing changed or added.

This is what i get when trying to start the console:
`Can’t load ‘C:\Users\{snip}\AppData\Local\Temp\par-742e6d65726b656c\cache-f6d413a946a68811a62a958c4938e0cf83468dc3\ed365286.xs.dll’ for module Net::SSLeay: load_file:Das angegebene Modul wurde nicht gefunden at /DynaLoader.pm line 193. at /PAR/Heavy.pm line 95. Compilation failed in require at C:\Users\{snip}\AppData\Local\Temp\par-742e6d65726b656c\cache-f6d413a946a68811a62a958c4938e0cf83468dc3\inc\lib/IO/Socket/SSL.pm line 19. BEGIN failed–compilation aborted at C:\Users\{snip}\AppData\Local\Temp\par-742e6d65726b656c\cache-f6d413a946a68811a62a958c4938e0cf83468dc3\inc\lib/IO/Socket/SSL.pm line 19. Compilation failed in require at script/ddclient line 34. BEGIN failed–compilation aborted at script/ddclient line 34.`

tm-107

**Comment by tdnguyen6** [comment]
I confirm that I also have the exact same issue. I'm on windows 11 though.

**Comment by knoxg** [comment]
Hmm I can't recreate that error but I ran a procmon trace over a cmdline invocation, and I think it's getting the libssl-1_1-x64__.dll out of my strawberry perl installation (which I use to build the PAR ). My cmdline was 

<pre>
C:\Users\knoxg>"C:\Program Files\ddclient\ddclient.exe" -verbose -force -ssl -foreground -file "C:\Program Files\ddclient\ddclient.conf" -cache "C:\Users\knoxg\AppData\Local\ddclient.cache"
</pre>

and in procmon I can see it created the ed365286.xs.dll in a temporary directory, and then opening that up and then trying to open libssl-1_1-x64__.dll, which fails, after which it starts searching trying to load it from dozens of other folders ( which are probably in my PATH or some registry key ).

Anyway will see if I can bundle the strawberry DLLs in there.

**Comment by knoxg** [comment]
Looks like the same issue encountered here: https://stackoverflow.com/questions/62462774/strawberry-perl-and-par-run-time-error-on-other-windows-machine-lwp-will-supp

**Comment by knoxg** [comment]
OK have added those DLLS via --link cmdline parameters to 'pp' and think it should work now.

Have released a 1.7.0 version downloadable from https://github.com/randomnoun/ddclient-nsis/tree/master/dist
