### ISSUE TITLE
Error in Cloudflare API

### ISSUE THREAD

**Issue by Deernose** [randomnoun/ddclient-nsis#7]
API Request Failed: GET /api/v4/zones/969151fe72ba684d611842a59e43367f/analytics/unreachability?limit=1&since=2021-11-07T01:28:25Z (undefined)

**Comment by knoxg** [comment]
There's not much there to go on ( I don't have a cloudflare account ), but it might be related to the missing DLL issues raised on https://github.com/randomnoun/ddclient-nsis/issues/6

Can you try using the latest 1.7.0 installer and see if you get any further ?

**Comment by sagz** [comment]
Cloudflare protocol now fails for a new reason: 
`FATAL:    Error loading the Perl module JSON::PP needed for cloudflare update.`

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/964843/158122054-bf1fb619-1599-410c-ae06-ae9f4f1dee86.png">

**Comment by hachi** [comment]
I've made a PR to include JSON::PP at https://github.com/randomnoun/ddclient-nsis/pull/9

**Comment by sagz** [comment]
Ooh. excited to see this change. Thanks @hachi !

Hoping it gets merged and part of the new release soon

**Comment by sagz** [comment]
Or is it possible for me to get one with these changes to test?

**Comment by knoxg** [comment]
I've merged in that PR and there's a new 1.8.0 distribution in the dist folder, can you see if that works ?

**Comment by knoxg** [comment]
Haven't heard back so I'm assuming this is fixed, will close this issue.

**Comment by marlop352** [comment]
@knoxg I'm getting an error when trying to use cloudflare:
`FAILED:   updating sub.domain.tld: invalid json or result.`
It's failing on the step where it decodes the json judging by when in the process is erroring out.

The only things that seems related and are different on the code of your version vs the 3.10.0 are:

Line 5577 (`(my $hostname = $domain) =~ s/\.$config{$key}{zone}$//;`)that doesn't exist on 3.10.0

Line 5597 that on your code is `$reply =~ s/^.*?\n\n//s;` and on 3.10.0 is `$reply =~ qr/{(?:[^{}]*|(?R))*}/mp;`
and the adjacent line 5598 that on your code is `my $response = eval {decode_json($reply)}` and on 3.10.0 is `my $response = eval {decode_json(${^MATCH})};`

Then later on the part that gets executed after the Zone ID is obtained the line pairs 5634/5635, 5661/5662 that are the same as 5597/5598 probably would error out assuming that this is the problem.
