### ISSUE TITLE
Opening ddclient.exe in Powershell fails due to config search in /etc/

### ISSUE THREAD

**Issue by sagz** [randomnoun/ddclient-nsis#8]
Is this working as intended?

```
PS C:\Program Files\ddclient> .\ddclient.exe
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
WARNING:  file /etc/ddclient/ddclient.conf: Cannot open file '/etc/ddclient/ddclient.conf'. (No such file or directory)
PS C:\Program Files\ddclient>
```

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/964843/158122258-8296e0fe-4710-43ad-8a03-2c0ea5c36b22.png">

**Comment by knoxg** [comment]
If you're running this from the command-line, you'll need a couple more command-line arguments with the location of the configuration file and the cache. 

The "Start ddclient console" shortcut created by the installer has these arguments (for my user):

<pre>
"C:\Program Files\ddclient\ddclient.exe" -foreground -file "C:\Program Files\ddclient\ddclient.conf" -cache "C:\Users\knoxg\AppData\Local\ddclient.cache"
</pre>

From within a powershell window, appears you need to supply a leading ampersand; i.e.

<pre>
PS C:\Users\knoxg> & "C:\Program Files\ddclient\ddclient.exe" -foreground -file "C:\Program Files\ddclient\ddclient.conf" -cache "C:\Users\knoxg\AppData\Local\ddclient.cache"
</pre>

But the installer creates a service which might be more convenient to run in the background. 
To start the service you might want to try
<pre>
C:\Windows\System32\net.exe start ddclient
</pre>
from an Administrator CMD shell, or

<pre>
Start-Service ddclient
</pre>
from an Administrator powershell

**Comment by knoxg** [comment]
Suppose we could return a more informative error message here, but this project is mostly a wrapper around the perl script rather than changes to that script. 

Hopefully you got this to work with the suggestions above, will close this ticket.
